 postgresql:
    image: postgres:12-alpine
    command: postgres -c log_statement=all
    ports:
      - 5432:5432
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: hogehoge
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    hostname: postgres
    restart: always
    user: root
